//*****************************************************************************
//*****************************************************************************
//  FILENAME: BP6.h
//   Version: 1.40, Updated on 2013/5/19 at 10:43:48                                          
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: BP6 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef BP6_INCLUDE
#define BP6_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  BP6_Stop
#pragma fastcall16  BP6_Start
#pragma fastcall16  BP6_On
#pragma fastcall16  BP6_Off
#pragma fastcall16  BP6_Switch
#pragma fastcall16  BP6_Invert
#pragma fastcall16  BP6_GetState


//-------------------------------------------------
// Constants for BP6 API's.
//-------------------------------------------------
//
#define  BP6_ON   1
#define  BP6_OFF  0

//-------------------------------------------------
// Prototypes of the BP6 API.
//-------------------------------------------------
extern void  BP6_Start(void);                                     
extern void  BP6_Stop(void);                                      
extern void  BP6_On(void);                                      
extern void  BP6_Off(void);                                      
extern void  BP6_Switch(BYTE bSwitch);
extern void  BP6_Invert(void);                                         
extern BYTE  BP6_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
