//*****************************************************************************
//*****************************************************************************
//  FILENAME: BP7.h
//   Version: 1.40, Updated on 2013/5/19 at 10:43:48                                          
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: BP7 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef BP7_INCLUDE
#define BP7_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  BP7_Stop
#pragma fastcall16  BP7_Start
#pragma fastcall16  BP7_On
#pragma fastcall16  BP7_Off
#pragma fastcall16  BP7_Switch
#pragma fastcall16  BP7_Invert
#pragma fastcall16  BP7_GetState


//-------------------------------------------------
// Constants for BP7 API's.
//-------------------------------------------------
//
#define  BP7_ON   1
#define  BP7_OFF  0

//-------------------------------------------------
// Prototypes of the BP7 API.
//-------------------------------------------------
extern void  BP7_Start(void);                                     
extern void  BP7_Stop(void);                                      
extern void  BP7_On(void);                                      
extern void  BP7_Off(void);                                      
extern void  BP7_Switch(BYTE bSwitch);
extern void  BP7_Invert(void);                                         
extern BYTE  BP7_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
