/******************************************************************************
*  Generated by PSoC Designer 5.4.2946
******************************************************************************/
#include <m8c.h>
// ONOFFPin address and mask defines
#pragma	ioport	ONOFFPin_Data_ADDR:	0x0
BYTE			ONOFFPin_Data_ADDR;
#pragma	ioport	ONOFFPin_DriveMode_0_ADDR:	0x100
BYTE			ONOFFPin_DriveMode_0_ADDR;
#pragma	ioport	ONOFFPin_DriveMode_1_ADDR:	0x101
BYTE			ONOFFPin_DriveMode_1_ADDR;
#pragma	ioport	ONOFFPin_DriveMode_2_ADDR:	0x3
BYTE			ONOFFPin_DriveMode_2_ADDR;
#pragma	ioport	ONOFFPin_GlobalSelect_ADDR:	0x2
BYTE			ONOFFPin_GlobalSelect_ADDR;
#pragma	ioport	ONOFFPin_IntCtrl_0_ADDR:	0x102
BYTE			ONOFFPin_IntCtrl_0_ADDR;
#pragma	ioport	ONOFFPin_IntCtrl_1_ADDR:	0x103
BYTE			ONOFFPin_IntCtrl_1_ADDR;
#pragma	ioport	ONOFFPin_IntEn_ADDR:	0x1
BYTE			ONOFFPin_IntEn_ADDR;
#define ONOFFPin_MASK 0x2
// ONOFFPin Shadow defines
//   ONOFFPin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define ONOFFPin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// BP6Pin address and mask defines
#pragma	ioport	BP6Pin_Data_ADDR:	0x0
BYTE			BP6Pin_Data_ADDR;
#pragma	ioport	BP6Pin_DriveMode_0_ADDR:	0x100
BYTE			BP6Pin_DriveMode_0_ADDR;
#pragma	ioport	BP6Pin_DriveMode_1_ADDR:	0x101
BYTE			BP6Pin_DriveMode_1_ADDR;
#pragma	ioport	BP6Pin_DriveMode_2_ADDR:	0x3
BYTE			BP6Pin_DriveMode_2_ADDR;
#pragma	ioport	BP6Pin_GlobalSelect_ADDR:	0x2
BYTE			BP6Pin_GlobalSelect_ADDR;
#pragma	ioport	BP6Pin_IntCtrl_0_ADDR:	0x102
BYTE			BP6Pin_IntCtrl_0_ADDR;
#pragma	ioport	BP6Pin_IntCtrl_1_ADDR:	0x103
BYTE			BP6Pin_IntCtrl_1_ADDR;
#pragma	ioport	BP6Pin_IntEn_ADDR:	0x1
BYTE			BP6Pin_IntEn_ADDR;
#define BP6Pin_MASK 0x4
// BP6Pin Shadow defines
//   BP6Pin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define BP6Pin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// BP7Pin address and mask defines
#pragma	ioport	BP7Pin_Data_ADDR:	0x0
BYTE			BP7Pin_Data_ADDR;
#pragma	ioport	BP7Pin_DriveMode_0_ADDR:	0x100
BYTE			BP7Pin_DriveMode_0_ADDR;
#pragma	ioport	BP7Pin_DriveMode_1_ADDR:	0x101
BYTE			BP7Pin_DriveMode_1_ADDR;
#pragma	ioport	BP7Pin_DriveMode_2_ADDR:	0x3
BYTE			BP7Pin_DriveMode_2_ADDR;
#pragma	ioport	BP7Pin_GlobalSelect_ADDR:	0x2
BYTE			BP7Pin_GlobalSelect_ADDR;
#pragma	ioport	BP7Pin_IntCtrl_0_ADDR:	0x102
BYTE			BP7Pin_IntCtrl_0_ADDR;
#pragma	ioport	BP7Pin_IntCtrl_1_ADDR:	0x103
BYTE			BP7Pin_IntCtrl_1_ADDR;
#pragma	ioport	BP7Pin_IntEn_ADDR:	0x1
BYTE			BP7Pin_IntEn_ADDR;
#define BP7Pin_MASK 0x10
// BP7Pin Shadow defines
//   BP7Pin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define BP7Pin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
// BP4Pin address and mask defines
#pragma	ioport	BP4Pin_Data_ADDR:	0x0
BYTE			BP4Pin_Data_ADDR;
#pragma	ioport	BP4Pin_DriveMode_0_ADDR:	0x100
BYTE			BP4Pin_DriveMode_0_ADDR;
#pragma	ioport	BP4Pin_DriveMode_1_ADDR:	0x101
BYTE			BP4Pin_DriveMode_1_ADDR;
#pragma	ioport	BP4Pin_DriveMode_2_ADDR:	0x3
BYTE			BP4Pin_DriveMode_2_ADDR;
#pragma	ioport	BP4Pin_GlobalSelect_ADDR:	0x2
BYTE			BP4Pin_GlobalSelect_ADDR;
#pragma	ioport	BP4Pin_IntCtrl_0_ADDR:	0x102
BYTE			BP4Pin_IntCtrl_0_ADDR;
#pragma	ioport	BP4Pin_IntCtrl_1_ADDR:	0x103
BYTE			BP4Pin_IntCtrl_1_ADDR;
#pragma	ioport	BP4Pin_IntEn_ADDR:	0x1
BYTE			BP4Pin_IntEn_ADDR;
#define BP4Pin_MASK 0x40
// BP4Pin Shadow defines
//   BP4Pin_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define BP4Pin_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
