//*****************************************************************************
//*****************************************************************************
//  FILENAME: BP4.h
//   Version: 1.40, Updated on 2013/5/19 at 10:43:48                                          
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: BP4 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef BP4_INCLUDE
#define BP4_INCLUDE

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  BP4_Stop
#pragma fastcall16  BP4_Start
#pragma fastcall16  BP4_On
#pragma fastcall16  BP4_Off
#pragma fastcall16  BP4_Switch
#pragma fastcall16  BP4_Invert
#pragma fastcall16  BP4_GetState


//-------------------------------------------------
// Constants for BP4 API's.
//-------------------------------------------------
//
#define  BP4_ON   1
#define  BP4_OFF  0

//-------------------------------------------------
// Prototypes of the BP4 API.
//-------------------------------------------------
extern void  BP4_Start(void);                                     
extern void  BP4_Stop(void);                                      
extern void  BP4_On(void);                                      
extern void  BP4_Off(void);                                      
extern void  BP4_Switch(BYTE bSwitch);
extern void  BP4_Invert(void);                                         
extern BYTE  BP4_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------



#endif
